import type { Metadata } from "next";
import { poppins } from "@/utils/font";
import Navbar from "@/components/navbar";
import { TooltipProvider } from "@/components/ui/tooltip";
import "./globals.css";
import ChatBot from "@/components/chatbot";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="id">
      <body className={poppins.className+" flex flex-col items-center w-screen"}>
        <AuthProvider>
          <TooltipProvider>
            <Navbar />
            {children}
            <ChatBot />
          </TooltipProvider>
        </AuthProvider>
      </body>
    </html>
  );
}